# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_core.ipynb.

# %% auto 0
__all__ = ['add3']

# %% ../nbs/01_core.ipynb 3
import pandas as pd

# %% ../nbs/01_core.ipynb 4
def add3(a,b,c): return a+b+c
